name: Basic cross-platform builds and checks
on:
  pull_request:
    branches: ["**"]

env:
  RUST_BACKTRACE: 1
  SHELL: /bin/bash

jobs:
  build-uwp-arm64:
    name: Build (Windows UWP arm64)
    runs-on: windows-2019
    steps:
      - name: Branch check
        if: ${{ !contains('refs/heads/auto refs/heads/try refs/heads/try-windows', github.ref) }}
        run: exit 0
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Copy to C drive
        run: cp D:\a C:\ -Recurse
      - name: Bootstrap
        working-directory: "C:\\a\\${{ github.event.repository.name }}\\${{ github.event.repository.name }}"
        run: |
          python -m pip install --upgrade pip virtualenv
          python mach fetch
      - name: Release build
        working-directory: "C:\\a\\${{ github.event.repository.name }}\\${{ github.event.repository.name }}"
        run: python mach build --release --target=aarch64-uwp-windows-msvc
